export const mockMediaData = [
  {
    id: 1,
    type: "image",
    src: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=400&h=600&fit=crop",
    aspectRatio: "9:16",
    prompt: "A cute animated poop emoji character walking on a sidewalk",
    title: "wyrdfiction",
    likes: 41,
    duration: null,
  },
  {
    id: 2,
    type: "video",
    src: "https://www.w3schools.com/html/mov_bbb.mp4",
    aspectRatio: "16:9",
    prompt: "Ethereal figure in glowing light, mystical atmosphere",
    title: "mystical_being",
    likes: 28,
    duration: "15s",
  },
  {
    id: 3,
    type: "image",
    src: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    aspectRatio: "1:1",
    prompt: "Portrait of an elderly man in vibrant green jacket",
    title: "street_portrait",
    likes: 156,
    duration: null,
  },
  {
    id: 5,
    type: "image",
    src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
    aspectRatio: "16:9",
    prompt: "Serene mountain landscape with misty peaks",
    title: "mountain_mist",
    likes: 203,
    duration: null,
  },
  {
    id: 6,
    type: "image",
    src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    aspectRatio: "1:1",
    prompt: "Modern minimalist portrait photography",
    title: "minimal_man",
    likes: 67,
    duration: null,
  },
  {
    id: 7,
    type: "video",
    src: "https://media.w3.org/2010/05/bunny/trailer.mp4",
    aspectRatio: "16:9",
    prompt: "Funny animal short film trailer",
    title: "bunny_trailer",
    likes: 180,
    duration: "50s",
  },
  {
    id: 8,
    type: "video",
    src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    aspectRatio: "9:16",
    prompt: "Cyberpunk city street at night with neon lights",
    title: "neon_dreams",
    likes: 89,
    duration: "30s",
  },
  {
    id: 9,
    type: "video",
    src: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    aspectRatio: "16:9",
    prompt: "Animated fantasy world adventure",
    title: "sintel_trailer",
    likes: 112,
    duration: "45s",
  },
];

export const allowedPrompts = [
  "A cute animated poop emoji character walking on a sidewalk",
  "Ethereal figure in glowing light, mystical atmosphere",
  "Portrait of an elderly man in vibrant green jacket",
  "Serene mountain landscape with misty peaks",
  "Modern minimalist portrait photography",
  "Funny animal short film trailer",
  "Cyberpunk city street at night with neon lights",
  "Animated fantasy world adventure",
];

export const soraOptions = {
  type: ["Image", "Video"],
  ratio: ["1:1", "2:3", "9:16", "16:9"],
  variations: ["1v", "2v", "4v"],
  resolution: ["480p", "720p", "1080p"],
  duration: ["15s", "30s", "45s", "50s"],
};
